import 'package:get/get.dart';
import 'package:training_newwave/model/autogenerated_entity.dart';
import 'package:training_newwave/model/detail_movie_entity.dart';
import 'package:training_newwave/movie_app/movie_with_set_state/movie_detail.dart';
import 'package:training_newwave/movie_app/networks/api_service.dart';

class MovieDetailController extends GetxController {
  int? id = 0;
  var loadCast = true.obs;
  var loadDetail = true.obs;
  var detailMovie = DetailMovie().obs;
  var listCast = <Cast>[].obs;

  MovieDetailController({this.id});

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
    getDetail();
    getCast();
  }

  void getCast() async {
    try {
      loadCast(true);
      final response = await ApiService.fetchAutogenerated(id!);
      listCast.value = response.cast;
      loadCast(false);
    } catch (e) {
      loadCast(true);
    }
  }

  void getDetail() async {
    try {
      loadDetail(true);
      final response = await ApiService.fetchDetail(id!);
      detailMovie.value = response;
      loadDetail(false);
    } catch (e) {
      loadDetail(true);
    }
  }
}
