import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/cupertino.dart';
import 'package:training_newwave/configs/app_constant.dart';
import 'package:training_newwave/configs/app_styles.dart';
import 'package:training_newwave/model/autogenerated_entity.dart';

class ItemCast extends StatelessWidget {

  final List<Cast> listCast ;
  final Cast cast;

  const ItemCast({Key key, this.listCast, this.cast}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 58,
      child: listCast.isEmpty
          ? const SizedBox()
          : Column(
        mainAxisAlignment: MainAxisAlignment.start,
        children: [
          ClipRRect(
            borderRadius: BorderRadius.circular(15),
            child: CachedNetworkImage(
              imageUrl: cast.profilePath != null
                  ? AppConstant.baseImage + cast.profilePath
                  : AppConstant.imageError,
              width: 50,
              height: 50,
              fit: BoxFit.cover,
            ),
          ),
          Padding(
            padding: const EdgeInsets.only(top: 8),
            child: Text(
              cast.name,
              maxLines: 2,
              textAlign: TextAlign.center,
              style: AppTextStyles.whiteS8Medium,
            ),
          ),
          Padding(
            padding: const EdgeInsets.only(
              top: 2,
              bottom: 22,
            ),
            child: Text(
              cast.character,
              maxLines: 2,
              textAlign: TextAlign.center,
              style: AppTextStyles.white50S8Medium,
            ),
          ),
        ],
      ),
    );
  }
}
