import 'package:flutter/cupertino.dart';
import 'package:training_newwave/model/autogenerated_entity.dart';
import 'package:training_newwave/model/detail_movie_entity.dart';
import 'package:training_newwave/model/enums/loading_status.dart';
import 'package:training_newwave/movie_app/networks/api_service.dart';

class DetailProvider extends ChangeNotifier {
  LoadingStatus loadDetailStatus = LoadingStatus.init;
  LoadingStatus loadCastStatus = LoadingStatus.init;
  late DetailMovie detailMovie;
  List<Cast> listCast = [];

  Future<void> getDetailMovie(int id) async {
    loadDetailStatus = LoadingStatus.loading;
    try {
      detailMovie = await ApiService.fetchDetail(id);
      loadDetailStatus = LoadingStatus.success;
      notifyListeners();
    } catch (e) {
      loadDetailStatus = LoadingStatus.failure;
    }
  }

  Future<void> getListCast(int id) async {
    loadCastStatus = LoadingStatus.loading;
    try {
      final response = await ApiService.fetchAutogenerated(id);
      listCast = response.cast ?? [];
      loadCastStatus = LoadingStatus.success;
      notifyListeners();
    } catch (e) {
      loadDetailStatus = LoadingStatus.failure;
    }
  }
}
