// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHcitMfG_oUu2DGNeZQa-kX2iULfy5sFo',
    appId: '1:348915048960:web:540bea0508d73d382beee5',
    messagingSenderId: '348915048960',
    projectId: 'notes-19573',
    authDomain: 'notes-19573.firebaseapp.com',
    storageBucket: 'notes-19573.appspot.com',
    measurementId: 'G-7EVZNB85WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjXJwQUeCQMxF1eXQYVbJurQ80yL2gHZo',
    appId: '1:348915048960:android:745e7d9acf8bec982beee5',
    messagingSenderId: '348915048960',
    projectId: 'notes-19573',
    storageBucket: 'notes-19573.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxpbbPt7FV0aX5DYPEGX7SFeZJoYuOIF4',
    appId: '1:348915048960:ios:7bdeaa4b514b3af42beee5',
    messagingSenderId: '348915048960',
    projectId: 'notes-19573',
    storageBucket: 'notes-19573.appspot.com',
    androidClientId: '348915048960-5qcd880ugi2ci527avq8g7n0kq6uh0ej.apps.googleusercontent.com',
    iosClientId: '348915048960-439q9p36va9kl5jg7jhubh4u5kcbgljj.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainingNewwave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxpbbPt7FV0aX5DYPEGX7SFeZJoYuOIF4',
    appId: '1:348915048960:ios:7bdeaa4b514b3af42beee5',
    messagingSenderId: '348915048960',
    projectId: 'notes-19573',
    storageBucket: 'notes-19573.appspot.com',
    androidClientId: '348915048960-5qcd880ugi2ci527avq8g7n0kq6uh0ej.apps.googleusercontent.com',
    iosClientId: '348915048960-439q9p36va9kl5jg7jhubh4u5kcbgljj.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainingNewwave',
  );
}
