import 'package:bloc/bloc.dart';
import 'package:training_newwave/movie_app/blocpattern/movie_detail_event.dart';
import 'package:training_newwave/movie_app/blocpattern/movie_detail_status.dart';
import 'package:training_newwave/movie_app/networks/api_service.dart';

class MovieDetailBloc extends Bloc<MovieDetailEvent, MovieDetailState> {

   int id;

  MovieDetailBloc({this.id}) : super(MovieDetailInitial()) {
    on<MovieDetailFetched>(
      (event, emit) async {
        try {
          emit(
            MovieDetailLoading(),
          );
          final detailMovie = await ApiService.fetchDetail(id);
          final autogenerated = await ApiService.fetchAutogenerated(id);
          emit(
            MovieDetailLoaded(
              autogenerated: autogenerated,
              detailMovie: detailMovie,
            ),
          );
        } catch (e) {
          emit(
            MovieDetailError(message: e.toString()),
          );
        }
      },
    );
  }
}
